# Generated by Django 5.1.2 on 2025-02-01 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_rename_last_updated_servicestatus_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.service'),
        ),
    ]
